version: "3"
services:
  preprocesser:
    build:
      context: ./docker/pre-processing
    volumes:
      - ./framework/pre-processing:/TFG/framework/pre-processing
      - ./framework/final-dataset:/TFG/framework/final-dataset
    working_dir: /TFG/framework/pre-processing
    command: tail -f /dev/null

  trainer:
    build:
      context: ./docker/train
    volumes:
      - ./framework/train:/TFG/framework/train
      - ./framework/final-dataset:/TFG/framework/final-dataset
    working_dir: /TFG/framework/train
    command: tail -f /dev/null
    deploy:
      resources:
        reservations:
          devices:
          - capabilities: [gpu]
