# LINUX Makefile

define help
Usage: make <command>
Commands:
  help:                         Show this help information
  train:                        Start training process
endef
export help

help:
	@echo "$$help"

train:
	python3 ./main.py
