# LINUX Makefile

define help
Usage: make <command>
Commands:
  help:                  Show this help information
  vicon-pre-processing	 Pre-process vicon dataset to feat NN input model.
endef
export help

help:
	@echo "$$help"

vicon-pre-processing:
	python3 pre-processing/scripts/processing.py